#!/bin/bash

PROJECT_ID=$(gcloud info --format='value(config.project)')
PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID --format="value(projectNumber)")
GKE_CLUSTER=jpa-istio-canary-demo
ZONE=europe-west4-a
